var express= require('express');
const bcrypt = require('bcrypt');
const jwt= require('jsonwebtoken');
//var popup = require('popups');
const auth = require('../config/authuser');
var router = express.Router();
const User= require('../model/user');
const app = express();
var _ = require('lodash');
const authadmin = require('../config/authadmin');

router.put('/client',authadmin, (req,res)=>{
  
    User.findOneAndUpdate({username:req.user.name},{$set:{'clientId':req.body.clientId}})       //to update client id generated by socket.io
    .then((user)=>{                                                                           // /api/update/client
        res.send(user);
    }).catch((err)=>{
        console.log(err);
    })
})

router.put('/connect',(req,res)=>{
   
  
    var len=(Object.keys(req.body).length);
    console.log(req.body);
  for(var i=0;i<len;i++){
    User.findOneAndUpdate({username:req.body[i].username},{$set:{connect:req.body[i].connect}})       //to update  whether willing to start connections
    .then((user)=>{                                                                           // /api/update/connnect
        res.end("1");
    }).catch((err)=>{
      console.log(err);
    })
};
//res.send('ok');
})

module.exports=router;